# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9714b9a97ae443a1f7b874d5759ccf84785475cc36d685329e766ac22900b1c1fe19d2c2b9d30d3a3e67675bc4b49c3cfba597ae4257840583a5e0ba0f83684

test:
  secret_key_base: f73426c87897288d9fb81c364872263d29bca67039d892734a8d2a8aac74976a65cb443ce25b4dff71efac1d310017567e0bfd1cd96a77a7a6c08d13d2d8ab8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
